<div class="card" style="width: 300rem;">
    <div class="card-body">
        <h5 class="card-title">Venta: <?= $venta->id ?></h5>
        <p class="card-text">productos_id: <?= $venta->productos_id ?></p>
        <p class="card-text">clientes_id: <?= $venta->clientes_id ?></p>
        <p class="card-text">empleados_id: <?= $venta->empleados_id ?></p>
        <p class="card-text">metodos_pago_id: <?= $venta->metodos_pago_id ?></p>
        <p class="card-text">fecha: <?= $venta->fecha ?></p>
        <p class="card-text">total: <?= $venta->total ?></p>
        <p class="card-text">por_pagar: <?= $venta->por_pagar ?></p>
        <p class="card-text">comentario: <?= $venta->comentario ?></p>
        <p class="card-text">forma_pago: <?= $venta->forma_pago ?></p>
        <p class="card-text">cancelada: <?= $venta->cancelada ?></p>
        <p class="card-text">status: <?= $venta->status ?></p>

        <img src="<?= PUBLIC_PATH ?>img/ventas/<?= $venta->id ?>.jpg" width="250px">
    </div>
</div>
