<div class="row">
    <div class="col-8">
        <form>
            <label class="control-label">Cliente: </label>
            <select name="cliente" class="form-control">
                <option value="1">Mayra</option>
                <option value="2">Kenia</option>
                <option value="100">Luis F</option>
            </select>
            <button class="btn btn-success">Seleccionar</button>
        </form>
    </div>
</div>

