<?php
View::template("plantilla");
?>

<h1>Categorías</h1>

<a href="<?=URL_APP?>/categorias/registrar" class="btn btn-primary">Registrar Categoría</a>
<style>
    .hidden-id { display: none; }
</style>
<table class="table table-striped table-hover" id="myTable">
    <thead>
    <tr>
        <th class="hidden-id">id</th> <!-- Ocultar encabezado -->
        <th>nombre</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($categorias as $p): ?>
        <tr>
            <td class="hidden-id"><?= $p->id ?></td> <!-- Ocultar celda -->
            <td><a href="<?=URL_APP?>/categorias/show/<?= $p->id ?>"><?= $p->nombre ?></a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<link rel="stylesheet" href="/DataTables/datatables.css" />

<script src="/DataTables/datatables.js"></script>
<script>
    let table = new DataTable('#myTable', {
    });
</script>

<!-- Botón Regresar -->
<?= Form::open() ?>
<?= Formbs::btn_regresar('Regresar', ['onclick' => 'window.history.back()']) ?>
<?= Form::close() ?>

<!-- Script para limpiar formulario -->
<script>
    function limpiarFormulario() {
        document.querySelector('form').reset();
    }
</script>
