<?= View::content() ?>
<?= Form::open() ?>

<label>id</label>
<?= Form::number('categorias.id',["class"=> "form-control", "title"=>"id de la categorias"]) ?>
<label>Nombre</label>
<?= Form::text('categorias.nombre',["class"=> "form-control", "title"=>"nombre de la categorias"]) ?>

<?= Form::open(['action' => 'categorias/registrar', 'enctype' => 'multipart/form-data']) ?>




<?= Formbs::btn_guardar('Guardar', ['type' => 'submit']) ?>
<?= Formbs::btn_limpiar('Limpiar', ['type' => 'button', 'onclick' => 'limpiarFormulario()']) ?>
<?= Formbs::btn_regresar('Regresar', ['onclick' => 'window.history.back()']) ?>
<?= Form::close() ?>
<!-- Script para limpiar formulario -->
<script>
    function limpiarFormulario() {
        document.querySelector('form').reset();
    }
</script>