<?= View::content() ?>
<?= Form::open() ?>

<label>id</label>
<?= Form::number('categorias.id',["class"=> "form-control", "title"=>"id de la categorias"]) ?>
<label>Nombre</label>
<?= Form::text('categorias.nombre',["class"=> "form-control", "title"=>"nombre de la categorias"]) ?>

<?= Form::open(['action' => 'categorias/registrar', 'enctype' => 'multipart/form-data']) ?>


<input type="file"
       class="filepond"
       name="filepond"
       multiple
       data-allow-reorder="true"
       data-max-file-size="3MB"
       data-max-files="3"
       accept="image/png, image/jpeg, image/gif">

<!-- Campo para subir la imagen -->
<div class="mb-3">
    <label class="form-label fs-6">Archivo</label>
    <input type="file" name="imagen" class="form-control" />
</div>

<!--<div class="mt-3">-->
<!--    --><?php //= Formbs::btn_aceptar('Guardar') ?>
<!--</div>-->
    <?= Formbs::btn_guardar('Guardar', ['type' => 'submit']) ?>
    <?= Formbs::btn_limpiar('Limpiar', ['type' => 'button', 'onclick' => 'limpiarFormulario()']) ?>
    <?= Formbs::btn_regresar('Regresar', ['onclick' => 'window.history.back()']) ?>
    <?= Form::close() ?>
    <!-- Script para limpiar formulario -->
    <script>
        function limpiarFormulario() {
            document.querySelector('form').reset();
        }
    </script>

