<?php
View::template("plantilla");
?>

<h1>ventas</h1>
<a href="<?=URL_APP?>/ventas/registrar" class="btn btn-primary">Registrar Categoría</a>
<style>
    .hide-id { display: none; }
</style>
<table class="table table-striped table-hover" id="myTable">
    <thead>
    <tr>
        <th class="hide-id">id</th>
        <th>Cliente</th>  <!-- Cambiado de "usuario_id" -->
        <th>Empleado</th> <!-- Cambiado de "empleados_id" -->
        <th>Método de Pago</th> <!-- Cambiado de "metodos_pago_id" -->
        <th>Fecha</th>
        <th>Total</th>
        <th>Por Pagar</th>
        <th>Comentario</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($ventas as $ven): ?>
        <tr>
            <td class="hide-id"><?= $ven->id ?></td>
            <td>
                <a href="<?=URL_APP?>/ventas/show/<?= $ven->id ?>">
                    <?= $ven->cliente_nombre  ?> <!-- Nombre del cliente -->
                </a>
            </td>
            <td><?=  $ven->empleados->nombre ?></td>
            <td><?=$ven->metodo_pago_id->nombre  ?></td>
            <td><?= $ven->fecha ?></td>
            <td><?= $ven->total ?></td>
            <td><?= $ven->por_pagar ?></td>
            <td><?= $ven->comentario ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<link rel="stylesheet" href="/DataTables/datatables.css" />
<script src="/DataTables/datatables.js"></script>
<script>
    let table = new DataTable('#myTable', {
        // config options...
    });
</script>

<?= Form::open() ?>

<!-- Botón Regresar -->
<?= Formbs::btn_regresar('Regresar', ['onclick' => 'window.history.back()']) ?>

<?= Form::close() ?>

<!-- Script para limpiar formulario -->
<script>
    function limpiarFormulario() {
        document.querySelector('form').reset();
    }
</script>
