<?php
View::template("plantilla");
?>

<h1>empleados</h1>
<a href="/Kumbiaphp/empleados/registrar" class="btn btn-primary">Registrar Categoría</a>

<table border="1" <table class="table table-striped table-hover" id="myTable">

    <thead>
    <tr>
        <th>id</th>
        <th>nombre</th>
        <th>email</th>
        <th>telefono</th>

    </tr>
    </thead>
    <tbody>
    <?php foreach ($empleados as $p): ?>
        <tr>
            <td><?= $p->id ?></td>
            <td><a href="http://localhost:80/Kumbiaphp/empleados/show/<?= $p->id ?>"><?= $p->nombre ?></a>

            <td><?= $p->email ?></td>
            <td><?= $p->telefono ?></td>

        </tr>
    <?php endforeach; ?>
    </tbody>





    <link rel="stylesheet" href="/DataTables/datatables.css" />

    <script src="/DataTables/datatables.js"></script>
    <script>
        let table = new DataTable('#myTable', {
            // config options...
        });
    </script>
</table>

</>

<?= Form::open() ?>
<?= Formbs::btn_regresar('Regresar', ['onclick' => 'window.history.back()']) ?>
<?= Form::close() ?>

