<?php
View::template("plantilla");
?>

<h1>Pagos</h1>
<a href="/Kumbiaphp/pagos/registrar" class="btn btn-primary">Registrar Categoría</a>

<table class="table table-striped table-hover" id="myTable">
    <thead>
    <tr>
        <th>id</th>
        <th>cliente_id</th>
        <th>metodo_pago_id</th>
        <th>total</th>
        <th>comentario</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($pagos as $p): ?>
        <tr>
            <!-- Enlace agregado al id para redirigir al show -->
            <td><a href="http://localhost/Kumbiaphp/pagos/show/<?= $p->id ?>"><?= $p->id ?></a></td>
            <td><?= $p->cliente_id ?></td>
            <td><?= $p->metodo_pago_id ?></td>
            <td><?= $p->total ?></td>
            <td><?= $p->comentario ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<link rel="stylesheet" href="/DataTables/datatables.css" />
<script src="/DataTables/datatables.js"></script>
<script>
    let table = new DataTable('#myTable', {
        // config options...
    });
</script>

<?= Form::open() ?>
<?= Formbs::btn_regresar('Regresar', ['onclick' => 'window.history.back()']) ?>
<?= Form::close() ?>
<script>
    function limpiarFormulario() {
        document.querySelector('form').reset();
    }
</script>
