<?php
View::template("plantilla");
?>

<h1>Metodos de Pago</h1>
<a href="/Kumbiaphp/metodos_pago/registrar" class="btn btn-primary">Registrar Categoría</a>

<table class="table table-striped table-hover" id="myTable">
    <thead>
    <tr>
        <th>id</th>
        <th>nombre</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($metodos_pago as $p): ?>
        <tr>
            <td><?= $p->id ?></td>
            <td><a href="http://localhost/Kumbiaphp/metodos_pago/show/<?= $p->id ?>"><?= $p->nombre ?></a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<!-- DataTables CSS -->
<link rel="stylesheet" href="/DataTables/datatables.css" />

<!-- DataTables JS -->
<script src="/DataTables/datatables.js"></script>

<script>
    // Configuración para habilitar la búsqueda y otras funcionalidades de DataTables
    let table = new DataTable('#myTable', {

    });
</script>

<?= Form::open() ?>
<?= Formbs::btn_regresar('Regresar', ['onclick' => 'window.history.back()']) ?>
<?= Form::close() ?>

<!-- Script para limpiar formulario -->
<script>
    function limpiarFormulario() {
        document.querySelector('form').reset();
    }
</script>
