<?= View::content() ?>
<?= Form::open() ?>

<label>id</label>
<?= Form::number('metodos_pago.id',["class"=> "form-control", "title"=>"id del metodos_pago"]) ?>
<label>Nombre</label>
<?= Form::text('metodos_pago.nombre',["class"=> "form-control", "title"=>"nombre del metodos_pago"]) ?>

<input type="file"
       class="filepond"
       name="filepond"
       multiple
       data-allow-reorder="true"
       data-max-file-size="3MB"
       data-max-files="3"
       accept="image/png, image/jpeg, image/gif">

<?= Formbs::btn_guardar('Guardar', ['type' => 'submit']) ?>
<?= Formbs::btn_limpiar('Limpiar', ['type' => 'button', 'onclick' => 'limpiarFormulario()']) ?>
<?= Formbs::btn_regresar('Regresar', ['onclick' => 'window.history.back()']) ?>
<?= Form::close() ?>

<!-- Script para limpiar formulario -->
<script>
    function limpiarFormulario() {
        document.querySelector('form').reset();
    }
</script>

