<?php
View::template("plantilla");
?>

<h1>Productos</h1>
<a href="/Kumbiaphp/productos/registrar" class="btn btn-primary">Registrar Categoría</a>

<table class="table table-striped table-hover" id="myTable">
    <thead>
    <tr>
        <th>ID</th>
        <th>categorias_id</th>
        <th>Nombre</th>
        <th>Precios</th>
        <th>Stock</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($productos as $p): ?>
        <tr>
            <td><a href="http://localhost/Kumbiaphp/productos/show/<?= $p->id ?>"><?= $p->id ?></a></td>
            <td><?= $p->categorias_id ?></td>
            <td><?= $p->nombre ?></td>
            <td><?= $p->precio ?></td>
            <td><?= $p->stock ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<!-- DataTables CSS -->
<link rel="stylesheet" href="/DataTables/datatables.css" />

<!-- DataTables JS -->
<script src="/DataTables/datatables.js"></script>

<script>
    // Configuración para habilitar la búsqueda y otras funcionalidades de DataTables
    let table = new DataTable('#myTable', {

    });
</script>

<?= Form::open() ?>

<!-- Botón Regresar -->
<?= Formbs::btn_regresar('Regresar', ['onclick' => 'window.history.back()']) ?>

<?= Form::close() ?>

<!-- Script para limpiar formulario -->
<script>
    function limpiarFormulario() {
        document.querySelector('form').reset();
    }
</script>
