<?php
$host = 'db-mysql-sfo3-58066-do-user-18079590-0.m.db.ondigitalocean.com';
$port = 25060; // Puerto actualizado
$db = 'PuntoVenta';
$user = 'doadmin';
$pass = 'AVNS_6-KQujFcvyFYZv3VV7X';
$charset = 'utf8';

$dsn = "mysql:host=$host;port=$port;dbname=$db;charset=$charset";

try {
    $pdo = new PDO($dsn, $user, $pass);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    echo "✅ Conexión exitosa a la base de datos '$db'";
} catch (PDOException $e) {
    echo "❌ Error de conexión: " . $e->getMessage();
}
?>