<?php
$host = '127.0.0.1';
$port = 3307; // Puerto actualizado
$db = 'PuntoVenta';
$user = 'web';
$pass = '123456789';
$charset = 'utf8';

$dsn = "mysql:host=$host;port=$port;dbname=$db;charset=$charset";

try {
    $pdo = new PDO($dsn, $user, $pass);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    echo "✅ Conexión exitosa a la base de datos '$db'";
} catch (PDOException $e) {
    echo "❌ Error de conexión: " . $e->getMessage();
}
?>