<div class="navbar-custom-menu">
    <ul class="nav navbar-nav">
        <!-- Messages: style can be found in dropdown.less-->
        <li class="dropdown messages-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-envelope-o"></i>
                <span class="label label-success">4</span>
            </a>
            <ul class="dropdown-menu">
                <li class="header">You have 4 messages</li>
                <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                        <li><!-- start message -->
                            <a href="#">
                                <div class="pull-left">
                                    <img src="<?=URL_APP?>/default/public/img/PERFIL/NAYE.jpg class="img-circle" alt="User Image"/>
                                </div>
                                <h4>
                                    Support Team
                                    <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                </h4>
                                <p>Why not buy a new awesome theme?</p>
                            </a>
                        </li><!-- end message -->
                    </ul>
                </li>
                <li class="footer"><a href="#">See All Messages</a></li>
            </ul>
        </li>
        <?php View::partial("admin/navbar_notifications"); ?>
        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <img src="<?=URL_APP?>/default/public/img/PERFIL/NAYE.jpg" class="user-image" alt="User Image"/>
                <span class="hidden-xs">ANAYELI RODRIGUEZ_21590397</span>
            </a>
            <ul class="dropdown-menu">
                <!-- User image -->
                <li class="user-header">
                    <img src="<?=URL_APP?>/default/public/img/PERFIL/NAYE.jpg" class="img-circle" alt="User Image" />
                    <p>
                        ANAYELI RODRIGUEZ - ING-SISTEMAS COMPUTACIONALES
                        <small>Member since ABRIL. 2025</small>
                    </p>
                </li>
                <!-- Menu Body -->
                <li class="user-body">
                    <div class="col-xs-4 text-center">
                        <a href="#">DINAMICA</a>
                    </div>
                    <div class="col-xs-4 text-center">
                        <a href="#">BUENA ACTITUD</a>
                    </div>
                    <div class="col-xs-4 text-center">
                        <a href="#">XD</a>
                    </div>
                </li>
                <!-- Menu Footer-->
                <li class="user-footer">
                    <div class="pull-left">
                        <a href="#" class="btn btn-default btn-flat">PERFIL</a>
                    </div>
                    <div class="pull-right">
                        <a href="#" class="btn btn-default btn-flat">Sign out</a>
                    </div>
                </li>
            </ul>
        </li>
    </ul>
</div>
