<ul class="sidebar-menu">
    <li class="header">MENU DE MI NEGOCIO</li>

    <!-- Dashboard Section -->
    <li class="treeview">
        <a href="#">
            <i class="fa fa-tachometer-alt"></i> <span>Dashboard</span>
        </a>
    </li>

    <!-- Categorías Section -->
    <li class="treeview">
        <a href="#">
            <i class="fa fa-th"></i> <span>CATEGORIAS</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="<?=URL_APP?>/categorias/index"><i class="fa fa-circle-o"></i> Ver Categorías</a></li>
        </ul>
    </li>

    <!-- Clientes Section -->
    <li class="treeview">
        <a href="#">
            <i class="fa fa-users"></i> <span>CLIENTES</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="<?=URL_APP?>/clientes/index"><i class="fa fa-circle-o"></i> Ver Clientes</a></li>
        </ul>
    </li>

    <!-- Detalles Ventas Section -->
    <li class="treeview">
        <a href="#">
            <i class="fa fa-shopping-cart"></i> <span>DETALLES VENTAS</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="<?=URL_APP?>/detalles_ventas/index"><i class="fa fa-circle-o"></i> Ver Detalles de Ventas</a></li>
        </ul>
    </li>

    <!-- Empleados Section -->
    <li class="treeview">
        <a href="#">
            <i class="fa fa-id-card"></i> <span>EMPLEADOS</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="<?=URL_APP?>/empleados/index"><i class="fa fa-circle-o"></i> Ver Empleados</a></li>
        </ul>
    </li>

    <!-- Métodos de Pago Section -->
    <li class="treeview">
        <a href="#">
            <i class="fa fa-credit-card"></i> <span>METODOS DE PAGO</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="<?=URL_APP?>/metodos_pago/index"><i class="fa fa-circle-o"></i> Ver Métodos de Pago</a></li>
        </ul>
    </li>

    <!-- Pagos Section -->
    <li class="treeview">
        <a href="#">
            <i class="fa fa-money-check-alt"></i> <span>PAGOS</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="<?=URL_APP?>/pagos/index"><i class="fa fa-circle-o"></i> Ver Pagos</a></li>
        </ul>
    </li>



    <!-- Productos Section -->
    <li class="treeview">
        <a href="#">
            <i class="fa fa-cogs"></i> <span>PRODUCTOS</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="<?=URL_APP?>/productos/index"><i class="fa fa-circle-o"></i> Ver Productos</a></li>
        </ul>
    </li>


    <!-- Ventas Section -->
    <li class="treeview">
        <a href="#">
            <i class="fa fa-chart-line"></i> <span>VENTAS</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="<?=URL_APP?>/ventas/index"><i class="fa fa-circle-o"></i> Ver Ventas</a></li>
        </ul>
    </li>


    <!-- Ventas Section -->
    <li class="treeview">
        <a href="#">
            <i class="fa fa-chart-line"></i> <span>PAGOS_ITEMS</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="<?=URL_APP?>/pagositems/index"><i class="fa fa-circle-o"></i> Ver pagos_items</a></li>
        </ul>
    </li>




    <!-- Ventas Section -->
    <li class="treeview">
        <a href="#">
            <i class="fa fa-chart-line"></i> <span>PRODUCTOS_LOG</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="<?=URL_APP?>/productos_log/index"><i class="fa fa-circle-o"></i> Ver productos_log</a></li>
        </ul>
    </li>





</ul>


