<!-- Card de Producto Log -->
<div class="col-md-6">
    <div class="card">
        <div class="card-header text-center">
            <h5>Producto Log: [<?= $producto_log->id ?>] - Producto ID: <?= $producto_log->producto_id ?></h5>
        </div>
        <div class="card-body">


            <!-- Imagen del Producto -->
            <img src="<?= PUBLIC_PATH ?>img/producto_log/<?= $producto_log->id ?>.jpg" width="250px" >

        </div>
    </div>
</div>
