<div class="card" style="width: 300rem;">
    <div class="card-body">
        <h5 class="card-title"> <?= $empleados->nombre ?></h5>
        <h6 class="card-subtitle mb-2 text-muted">email: <?= $empleados->email ?></h6>
        <p class="card-text">Telefono: <?= $empleados->telefono ?></p>


        <img src="<?= PUBLIC_PATH ?>img/empleados/<?= $empleados->id ?>.png" width="250px">
    </div>
</div>
