<h4 class="mt-4">  ventas_pendientes_de_pago </h4>
<form action="<?= URL_APP ?>/pagos/finalizar/<?= $cliente_id?>">
    <table class="table table-sm table-hover table-striped" >
    <thead>

    <tr>
        <th>id</th>
        <th>fecha</th>
        <th>total</th>
        <th>abonado</th>
        <th>por_pagar</th>

    </tr>
    </thead>
        <tbody>
        <?php foreach ($ventas as $v): ?>
        <tr>
            <td><?= $v-> id?> </td>
            <td><?= $v-> created_at?> </td>
            <td><?= $v-> total?> </td>
            <td><?= $v-> total - $v ->por_pagar?> </td>
            <td><?= $v-> por_pagar?> </td>
            <td><input name="ventas [<?= $v-> id?>]" type="text"></td>

        </tr>
        <?php endforeach;?>
        </tbody>
    </table>
    <button type ="sumbit">pagar</button>
</form>